---
deployment:
  tasks:
    - tar --exclude='.git' -cf - . | tar -xf - -C /home/csgocomp/src/
    - source ~/.nvm/nvm.sh
    - nvm use 16
    - cd /home/csgocomp/src && npm install
    - cd /home/csgocomp/src && pkill -f "node" || true
    - cd /home/csgocomp/src && npm run start &