---
deployment:
  tasks:
    - find . -not -path './.git/*' -not -name '.git' | cp -r --parents -t /home/csgocomp/src/
    - source ~/.nvm/nvm.sh
    - nvm use 16
    - cd /home/csgocomp/src && npm install
    - cd /home/csgocomp/src && pkill -f "node" || true
    - cd /home/csgocomp/src && npm run start &